/* Cache-first over a versioned precache. PRECACHE is generated by
   tools/build.mjs — do not hand-edit the list. Offline is the normal case for
   this product, not a degraded one. */

const VERSION = "5a0734bc7e4b";
const CACHE = `fp-${VERSION}`;

/* __PRECACHE_START__ */
const PRECACHE = [
  "./",
  "assets/fonts/baloo-2-latin-600-normal.woff2",
  "assets/fonts/nunito-latin-400-normal.woff2",
  "assets/fonts/nunito-latin-700-normal.woff2",
  "assets/icon-192.png",
  "assets/icon-512.png",
  "assets/icon-maskable.png",
  "assets/mark.svg",
  "content/authored.json",
  "content/cells/01-city-in-a-speck.json",
  "content/cells/02-the-wall-that-chooses.json",
  "content/cells/03-the-power-plant.json",
  "content/cells/04-the-instruction-room.json",
  "content/cells/05-build-a-cell.json",
  "content/curriculum.json",
  "content/evolution/01-what-would-change-your-mind.json",
  "content/evolution/02-the-same-bones-in-different-jobs.json",
  "content/evolution/03-the-order-in-the-rocks.json",
  "content/evolution/04-family-trees-written-in-dna.json",
  "content/evolution/05-how-much-can-change.json",
  "content/hints.json",
  "content/natural-selection/01-the-beetles-that-vanished.json",
  "content/reviews.json",
  "content/what-is-life/04-could-life-start-by-itself.json",
  "css/app.css",
  "index.html",
  "js/app.js",
  "js/components/board.js",
  "js/components/predict.js",
  "js/components/quiz.js",
  "js/components/slider.js",
  "js/curriculum.js",
  "js/el.js",
  "js/icons.js",
  "js/lesson/runner.js",
  "js/lesson/tutor.js",
  "js/lesson/view.js",
  "js/level.js",
  "js/reward.js",
  "js/scheduler.js",
  "js/screens.js",
  "js/sims/base.js",
  "js/sims/energy.js",
  "js/sims/membrane.js",
  "js/sims/selection.js",
  "js/state.js",
  "manifest.webmanifest"
];
/* __PRECACHE_END__ */

self.addEventListener("install", (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(PRECACHE)).then(() => self.skipWaiting()));
});

self.addEventListener("activate", (e) => {
  e.waitUntil(
    caches.keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  );
});

self.addEventListener("fetch", (e) => {
  const { request } = e;
  if (request.method !== "GET" || new URL(request.url).origin !== location.origin) return;

  // Hash routing means every in-app route IS the shell document, so a cold
  // offline start needs the shell as a fallback. But falling back to the shell
  // for *every* navigation silently shadows any other real page at this origin
  // — styleguide.html was served index.html and looked like a broken build.
  // Try the exact document first; use the shell only when there isn't one.
  if (request.mode === "navigate") {
    e.respondWith(
      caches.match(request)
        .then((hit) => hit || fetch(request))
        .catch(() => caches.match("./"))
    );
    return;
  }

  e.respondWith(
    caches.match(request).then((hit) =>
      hit || fetch(request).then((res) => {
        // Only same-origin OK responses are worth keeping; opaque ones lie
        // about their status and poison the cache.
        if (res.ok) {
          const copy = res.clone();
          caches.open(CACHE).then((c) => c.put(request, copy));
        }
        return res;
      }).catch(() => hit)
    )
  );
});
